// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RugbyEngine.Api.Data;

#nullable disable

namespace RugbyEngine.Api.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20260404053605_FixLastLoginSeed")]
    partial class FixLastLoginSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RugbyEngine.Api.Data.Entities.Cuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("BorradoLogico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("DType")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Cuenta");
                });

            modelBuilder.Entity("RugbyEngine.Api.Data.Entities.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("BorradoLogico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TipoEventoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("TipoEventoId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("RugbyEngine.Api.Data.Entities.EventoCuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("BorradoLogico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<int>("CuentaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("integer");

                    b.Property<int>("EventoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CuentaId");

                    b.HasIndex("DeletedById");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("EventoId", "CuentaId")
                        .IsUnique();

                    b.ToTable("EventoCuentas");
                });

            modelBuilder.Entity("RugbyEngine.Api.Data.Entities.EventoMovimientos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("BorradoLogico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("integer");

                    b.Property<int>("EventoId")
                        .HasColumnType("integer");

                    b.Property<int>("MovimientoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("MovimientoId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("EventoId", "MovimientoId")
                        .IsUnique();

                    b.ToTable("EventoMovimientos");
                });

            modelBuilder.Entity("RugbyEngine.Api.Data.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("BorradoLogico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("integer");

                    b.Property<string>("Icono")
                        .HasColumnType("text");

                    b.Property<int>("Lvl")
                        .HasColumnType("integer");

                    b.Property<int?>("MenuPadreId")
                        .HasColumnType("integer");

                    b.Property<int?>("PermisoId")
                        .HasColumnType("integer");

                    b.Property<string>("Ruta")
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ToolTip")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("MenuPadreId");

                    b.HasIndex("PermisoId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Menu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BorradoLogico = false,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 1,
                            Lvl = 0,
                            PermisoId = 8,
                            Titulo = "Entrenamientos"
                        },
                        new
                        {
                            Id = 4,
                            BorradoLogico = false,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 1,
                            Lvl = 0,
                            PermisoId = 2,
                            Titulo = "Tesoreria"
                        },
                        new
                        {
                            Id = 5,
                            BorradoLogico = false,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 1,
                            Lvl = 0,
                            PermisoId = 6,
                            Titulo = "Administracion"
                        },
                        new
                        {
                            Id = 7,
                            BorradoLogico = false,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 1,
                            Lvl = 1,
                            MenuPadreId = 5,
                            PermisoId = 3,
                            Titulo = "Registro"
                        },
                        new
                        {
                            Id = 11,
                            BorradoLogico = false,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 1,
                            Lvl = 1,
                            MenuPadreId = 4,
                            PermisoId = 5,
                            Ruta = "/Tesoreria/3T",
                            Titulo = "3T"
                        },
                        new
                        {
                            Id = 10,
                            BorradoLogico = false,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 1,
                            Lvl = 2,
                            MenuPadreId = 7,
                            PermisoId = 4,
                            Ruta = "/Admin/Registro/Personas",
                            Titulo = "Personas"
                        },
                        new
                        {
                            Id = 12,
                            BorradoLogico = false,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 1,
                            Lvl = 2,
                            MenuPadreId = 11,
                            PermisoId = 5,
                            Ruta = "/Tesoreria/3T/Pagos",
                            Titulo = "Pagos"
                        },
                        new
                        {
                            Id = 14,
                            BorradoLogico = false,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 1,
                            Lvl = 2,
                            MenuPadreId = 7,
                            PermisoId = 1,
                            Ruta = "/Admin/Registro/Usuarios",
                            Titulo = "Usuarios"
                        },
                        new
                        {
                            Id = 15,
                            BorradoLogico = false,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 1,
                            Lvl = 2,
                            MenuPadreId = 1,
                            PermisoId = 9,
                            Ruta = "/Entrenamientos/Asistencia",
                            Titulo = "Asistencia"
                        });
                });

            modelBuilder.Entity("RugbyEngine.Api.Data.Entities.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("BorradoLogico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("integer");

                    b.Property<int>("EnviaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecibeId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoMovimientoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("RecibeId");

                    b.HasIndex("TipoMovimientoId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("EnviaId", "RecibeId", "TipoMovimientoId", "Fecha")
                        .IsUnique()
                        .HasDatabaseName("IX_Movimiento_Unicidad");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("RugbyEngine.Api.Data.Entities.MovimientoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("BorradoLogico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MovimientoId")
                        .HasColumnType("integer");

                    b.Property<string>("Producto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("MovimientoId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("MovimientoItems");
                });

            modelBuilder.Entity("RugbyEngine.Api.Data.Entities.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("BorradoLogico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Perfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BorradoLogico = false,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 1,
                            Descripcion = "Acceso Total",
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            BorradoLogico = false,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 1,
                            Descripcion = "Entrenador",
                            Nombre = "Entrenador"
                        },
                        new
                        {
                            Id = 4,
                            BorradoLogico = false,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 1,
                            Descripcion = "Usuario General",
                            Nombre = "Jugador"
                        });
                });

            modelBuilder.Entity("RugbyEngine.Api.Data.Entities.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("BorradoLogico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Permisos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BorradoLogico = false,
                            Codigo = "admin",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 1,
                            Descripcion = "Administrador del sistema",
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            BorradoLogico = false,
                            Codigo = "tesoreria",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 1,
                            Descripcion = "Acceso a Tesoreria",
                            Nombre = "Tesoreria"
                        },
                        new
                        {
                            Id = 3,
                            BorradoLogico = false,
                            Codigo = "registros",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 1,
                            Descripcion = "Acceso a Registros",
                            Nombre = "Registros"
                        },
                        new
                        {
                            Id = 4,
                            BorradoLogico = false,
                            Codigo = "personas",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 1,
                            Descripcion = "Acceso a Personas",
                            Nombre = "Personas"
                        },
                        new
                        {
                            Id = 5,
                            BorradoLogico = false,
                            Codigo = "3t",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 1,
                            Descripcion = "Acceso a 3T",
                            Nombre = "3T"
                        },
                        new
                        {
                            Id = 6,
                            BorradoLogico = false,
                            Codigo = "administracion",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 1,
                            Descripcion = "Acceso a Administracion",
                            Nombre = "Administracion"
                        },
                        new
                        {
                            Id = 7,
                            BorradoLogico = false,
                            Codigo = "usuarios",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 1,
                            Descripcion = "Acceso a Usuarios",
                            Nombre = "Usuarios"
                        },
                        new
                        {
                            Id = 8,
                            BorradoLogico = false,
                            Codigo = "entrenamientos",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 1,
                            Descripcion = "Acceso a Entrenamientos",
                            Nombre = "Entrenamientos"
                        },
                        new
                        {
                            Id = 9,
                            BorradoLogico = false,
                            Codigo = "asistencia",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 1,
                            Descripcion = "Acceso a Asistencia",
                            Nombre = "Asistencia"
                        });
                });

            modelBuilder.Entity("RugbyEngine.Api.Data.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("BorradoLogico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Cobertura")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("integer");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Domicilio")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NroAfiliado")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("Documento")
                        .IsUnique();

                    b.HasIndex("UpdatedById");

                    b.ToTable("Persona");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellidos = "Gigena",
                            BorradoLogico = false,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 1,
                            Documento = "44590912",
                            Email = "agustingigena1704@gmail.com",
                            FechaNacimiento = new DateOnly(2000, 1, 1),
                            Nombres = "Agustin"
                        });
                });

            modelBuilder.Entity("RugbyEngine.Api.Data.Entities.PersonaCuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("BorradoLogico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("CuentaId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CuentaId");

                    b.HasIndex("PersonaId", "CuentaId")
                        .IsUnique();

                    b.ToTable("PersonaCuentas");
                });

            modelBuilder.Entity("RugbyEngine.Api.Data.Entities.TipoEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("BorradoLogico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("TiposEvento");
                });

            modelBuilder.Entity("RugbyEngine.Api.Data.Entities.TipoMovimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("BorradoLogico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("TiposMovimiento");
                });

            modelBuilder.Entity("RugbyEngine.Api.Data.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("BorradoLogico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("PersonaId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BorradoLogico = false,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = 1,
                            Email = "agustingigena1704@gmail.com",
                            LastLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$11$knIWvYSD.JF1fM.2GKgZ4eMdCFDV26H/hEVyj5A9upJwIPIVFXZI.",
                            Username = "agigena"
                        });
                });

            modelBuilder.Entity("UsuarioPerfil", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("PerfilId")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId", "PerfilId");

                    b.HasIndex("PerfilId");

                    b.ToTable("UsuarioPerfil", (string)null);
                });

            modelBuilder.Entity("UsuarioPermiso", b =>
                {
                    b.Property<int>("PerfilId")
                        .HasColumnType("integer");

                    b.Property<int>("PermisoId")
                        .HasColumnType("integer");

                    b.HasKey("PerfilId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("PerfilPermiso", (string)null);

                    b.HasData(
                        new
                        {
                            PerfilId = 1,
                            PermisoId = 1
                        },
                        new
                        {
                            PerfilId = 1,
                            PermisoId = 2
                        },
                        new
                        {
                            PerfilId = 1,
                            PermisoId = 3
                        },
                        new
                        {
                            PerfilId = 1,
                            PermisoId = 4
                        },
                        new
                        {
                            PerfilId = 1,
                            PermisoId = 5
                        },
                        new
                        {
                            PerfilId = 1,
                            PermisoId = 6
                        },
                        new
                        {
                            PerfilId = 1,
                            PermisoId = 7
                        },
                        new
                        {
                            PerfilId = 1,
                            PermisoId = 8
                        },
                        new
                        {
                            PerfilId = 1,
                            PermisoId = 9
                        },
                        new
                        {
                            PerfilId = 2,
                            PermisoId = 3
                        },
                        new
                        {
                            PerfilId = 2,
                            PermisoId = 4
                        },
                        new
                        {
                            PerfilId = 2,
                            PermisoId = 6
                        },
                        new
                        {
                            PerfilId = 2,
                            PermisoId = 8
                        },
                        new
                        {
                            PerfilId = 2,
                            PermisoId = 9
                        });
                });

            modelBuilder.Entity("RugbyEngine.Api.Data.Entities.Evento", b =>
                {
                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RugbyEngine.Api.Data.Entities.TipoEvento", "TipoEvento")
                        .WithMany()
                        .HasForeignKey("TipoEventoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("TipoEvento");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("RugbyEngine.Api.Data.Entities.EventoCuenta", b =>
                {
                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RugbyEngine.Api.Data.Entities.Cuenta", "Cuenta")
                        .WithMany()
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RugbyEngine.Api.Data.Entities.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("Cuenta");

                    b.Navigation("DeletedBy");

                    b.Navigation("Evento");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("RugbyEngine.Api.Data.Entities.EventoMovimientos", b =>
                {
                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RugbyEngine.Api.Data.Entities.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RugbyEngine.Api.Data.Entities.Movimiento", "Movimiento")
                        .WithMany()
                        .HasForeignKey("MovimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("Evento");

                    b.Navigation("Movimiento");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("RugbyEngine.Api.Data.Entities.Menu", b =>
                {
                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RugbyEngine.Api.Data.Entities.Menu", "MenuPadre")
                        .WithMany()
                        .HasForeignKey("MenuPadreId");

                    b.HasOne("RugbyEngine.Api.Data.Entities.Permiso", "Permiso")
                        .WithMany()
                        .HasForeignKey("PermisoId");

                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("MenuPadre");

                    b.Navigation("Permiso");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("RugbyEngine.Api.Data.Entities.Movimiento", b =>
                {
                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RugbyEngine.Api.Data.Entities.Cuenta", "Envia")
                        .WithMany()
                        .HasForeignKey("EnviaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RugbyEngine.Api.Data.Entities.Cuenta", "Recibe")
                        .WithMany()
                        .HasForeignKey("RecibeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RugbyEngine.Api.Data.Entities.TipoMovimiento", "TipoMovimiento")
                        .WithMany()
                        .HasForeignKey("TipoMovimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("Envia");

                    b.Navigation("Recibe");

                    b.Navigation("TipoMovimiento");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("RugbyEngine.Api.Data.Entities.MovimientoItem", b =>
                {
                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RugbyEngine.Api.Data.Entities.Movimiento", "Movimiento")
                        .WithMany("Items")
                        .HasForeignKey("MovimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("Movimiento");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("RugbyEngine.Api.Data.Entities.Perfil", b =>
                {
                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("RugbyEngine.Api.Data.Entities.Permiso", b =>
                {
                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("RugbyEngine.Api.Data.Entities.Persona", b =>
                {
                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("RugbyEngine.Api.Data.Entities.PersonaCuenta", b =>
                {
                    b.HasOne("RugbyEngine.Api.Data.Entities.Cuenta", "Cuenta")
                        .WithMany("PersonaCuentas")
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RugbyEngine.Api.Data.Entities.Persona", "Persona")
                        .WithMany("PersonaCuentas")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cuenta");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("RugbyEngine.Api.Data.Entities.TipoEvento", b =>
                {
                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("RugbyEngine.Api.Data.Entities.Usuario", b =>
                {
                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RugbyEngine.Api.Data.Entities.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId");

                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("Persona");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("UsuarioPerfil", b =>
                {
                    b.HasOne("RugbyEngine.Api.Data.Entities.Perfil", null)
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RugbyEngine.Api.Data.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UsuarioPermiso", b =>
                {
                    b.HasOne("RugbyEngine.Api.Data.Entities.Perfil", null)
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RugbyEngine.Api.Data.Entities.Permiso", null)
                        .WithMany()
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RugbyEngine.Api.Data.Entities.Cuenta", b =>
                {
                    b.Navigation("PersonaCuentas");
                });

            modelBuilder.Entity("RugbyEngine.Api.Data.Entities.Movimiento", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("RugbyEngine.Api.Data.Entities.Persona", b =>
                {
                    b.Navigation("PersonaCuentas");
                });
#pragma warning restore 612, 618
        }
    }
}
